[package]
name = "as3.lang"
version = "1.0.0"
authors = ["Matheus Dias de Souza <hydroperfox@gmail.com>"]
license = "Apache-2.0"
description = "The ActionScript 3 language built-ins."
source-path = ["src"]

[dependencies]
